### ISSUE TITLE
Desenvolvimento do Front-End

### ISSUE THREAD

**Issue by LayaneBentes** [victo-dev-qriarlabs/heavenly#16]
Descrição: Esta tarefa envolve a implementação da interface de usuário do site usando React, com base nos designs finalizados. O objetivo é transformar os designs fornecidos em um site funcional e interativo, utilizando as melhores práticas de desenvolvimento front-end com React.

Tarefas referentes

- [x] #2 Seguir o designer implementado na tarefa.
- [x] #7 Seguir o padrão estabelecido para deploy. 
- [x] #4 Configurar seu ambiente dev com as staks.
- [x] #15 seguir a estrutura de pasta estabelecida.
- [x] #14 
- [x] #10 
- [x] #22  finalizei essa tarefa na sprint 2 e adicionei uma nova tarefa mais refinada, segue a tarefa logo abaixo:
- [x] #32 
- [x] #31

**Comment by ProBeta12** [comment]
Tarefa feita para organizar o ambiente dev e sua produção.
